name: Build docs and cache shell
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: datakurre
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: >
        make -C docs nix-ci-html;
        touch docs/_build/html/.nojekyll
    - uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        branch: gh-pages
        folder: docs/_build/html
        single-commit: true
# devenv-test:
#   concurrency: ci-${{ github.ref }}
#   runs-on: ubuntu-latest
#   steps:
#   - uses: actions/checkout@v4
#   - uses: cachix/install-nix-action@v30
#     with:
#       nix_path: nixpkgs=channel:nixos-unstable
#   - uses: cachix/cachix-action@v15
#     with:
#       name: datakurre
#       authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
#       extraPullNames: devenv
#   - run: nix profile install nixpkgs#devenv
#   - run: >
#       echo '{ cachix.push = "datakurre"; }' > devenv.local.nix
#   - run: >
#       devenv test
#     env:
#       CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
#   - run: >
#       devenv shell -- echo "Ok."
#     env:
#       CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
