name: "build"
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: datakurre
#       signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: >
        make -C docs nix-html
        touch docs/_build/html/.nojekyll;
    - uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        branch: gh-pages
        folder: docs/_build/html
        single-commit: true
