name: Test and cache environment
on: [push]
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: datakurre
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: devenv
    - run: nix profile install nixpkgs#devenv
    - run: >
        echo { cachix.push = "datakurre"; }' > devenv.local.nix
    - run: devenv test
